wm:
  # dataloader
  dataset_path: "./data/"
  dataset_split: 0.8
  device: "cuda"

  img_width: 128
  img_height: 128
  batch_size: 6
  seq_length: 90
  embed_dim: 9216
  action_dim: 2
  deter_dim: 1024
  stoch_dim: 32
  stoch_rank: 32
  hidden_dim: 1000

  # Loss
  image_weight: 2.0
  kl_balance: 0.8
  kl_weight: 0.1

  lr: 3e-4
  eps: 1e-5